name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, pypy3]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # https://github.com/marketplace/actions/setup-ffmpeg
      - name: Install & setup FFMPEG
        uses: FedericoCarboni/setup-ffmpeg@v1-beta
      # https://github.com/ymyzk/tox-gh-actions
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
